import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

/** Standard shadcn/ui `cn` helper: merge class names, last conflicting utility wins. */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

/** Trigger a browser download for generated bytes. */
export function downloadBytes(bytes: Uint8Array, fileName: string, mimeType = 'application/pdf'): void {
  const blob = new Blob([bytes as unknown as BlobPart], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = fileName
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  URL.revokeObjectURL(url)
}

export function downloadText(text: string, fileName: string): void {
  downloadBytes(new TextEncoder().encode(text), fileName, 'text/plain')
}
