/**
 * Country name to ISO 3166-1 alpha-2, and back to the name a picker shows.
 *
 * FedEx Ship Manager stores country of manufacture as `GB`, `MY`, `JP`, `US` — the CIPL
 * prints `United Kingdom`, `Malaysia`, `Japan`, `United States`. Typing the long name into
 * that column does not fail loudly; it just is not the code the commodity record needs.
 *
 * All 249 assigned codes, generated from the ISO register rather than added as they turn
 * up. The list used to hold about fifty, which is how a shipment of goods made in the
 * Dominican Republic reached the operator as `(not recognised — enter the two-letter code)`
 * on two of its six commodity rows. A country nobody thought to add is not rare enough to
 * be worth that.
 *
 * Still deliberately not fuzzy. An unknown name is returned unchanged and flagged rather
 * than guessed at — a wrong country of manufacture is a customs misdeclaration, and there is
 * no version of guessing that is safer than asking.
 */

/** The everyday name for each code, which is what a country picker lists. */
const NAMES: Record<string, string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AG: 'Antigua and Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antarctica',
  AR: 'Argentina',
  AS: 'American Samoa',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Åland Islands',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Saint Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia',
  BQ: 'Bonaire',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet Island',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Cocos (Keeling) Islands',
  CD: 'Congo (Kinshasa)',
  CF: 'Central African Republic',
  CG: 'Congo (Brazzaville)',
  CH: 'Switzerland',
  CI: 'Côte d\'Ivoire',
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curaçao',
  CX: 'Christmas Island',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'Western Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  FO: 'Faroe Islands',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'French Guiana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GS: 'South Georgia and the South Sandwich Islands',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HM: 'Heard Island and McDonald Islands',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'India',
  IO: 'British Indian Ocean Territory',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KP: 'North Korea',
  KR: 'South Korea',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MF: 'Saint Martin',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MP: 'Northern Mariana Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NF: 'Norfolk Island',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'French Polynesia',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PM: 'Saint Pierre and Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestine',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Islands',
  SC: 'Seychelles',
  SD: 'Sudan',
  SE: 'Sweden',
  SG: 'Singapore',
  SH: 'Saint Helena',
  SI: 'Slovenia',
  SJ: 'Svalbard and Jan Mayen',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'South Sudan',
  ST: 'Sao Tome and Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  SY: 'Syria',
  SZ: 'Eswatini',
  TC: 'Turks and Caicos Islands',
  TD: 'Chad',
  TF: 'French Southern Territories',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TR: 'Türkiye',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VA: 'Holy See',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuela',
  VG: 'British Virgin Islands',
  VI: 'U.S. Virgin Islands',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis and Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
}

/**
 * Every spelling that resolves to a code: the ISO register's own name, the everyday name
 * where those differ, the part before a comma or bracket (`Korea, Republic of` also answers
 * to `Korea`), and the abbreviations an ERP actually prints.
 */
const ISO_ALPHA2: Record<string, string> = {
  afghanistan: 'AF',
  albania: 'AL',
  algeria: 'DZ',
  'american samoa': 'AS',
  andorra: 'AD',
  angola: 'AO',
  anguilla: 'AI',
  antarctica: 'AQ',
  'antigua and barbuda': 'AG',
  argentina: 'AR',
  armenia: 'AM',
  aruba: 'AW',
  australia: 'AU',
  austria: 'AT',
  azerbaijan: 'AZ',
  bahamas: 'BS',
  bahrain: 'BH',
  bangladesh: 'BD',
  barbados: 'BB',
  belarus: 'BY',
  belgium: 'BE',
  belize: 'BZ',
  benin: 'BJ',
  bermuda: 'BM',
  bhutan: 'BT',
  bolivia: 'BO',
  'bolivia, plurinational state of': 'BO',
  bonaire: 'BQ',
  'bonaire, sint eustatius and saba': 'BQ',
  'bosnia and herzegovina': 'BA',
  botswana: 'BW',
  'bouvet island': 'BV',
  brazil: 'BR',
  'british indian ocean territory': 'IO',
  'british virgin islands': 'VG',
  brunei: 'BN',
  'brunei darussalam': 'BN',
  bulgaria: 'BG',
  'burkina faso': 'BF',
  burma: 'MM',
  burundi: 'BI',
  'cabo verde': 'CV',
  cambodia: 'KH',
  cameroon: 'CM',
  canada: 'CA',
  'cape verde': 'CV',
  'cayman islands': 'KY',
  'central african republic': 'CF',
  chad: 'TD',
  chile: 'CL',
  china: 'CN',
  'china, people\'s republic of': 'CN',
  'chinese taipei': 'TW',
  'christmas island': 'CX',
  cocos: 'CC',
  'cocos (keeling) islands': 'CC',
  colombia: 'CO',
  comoros: 'KM',
  congo: 'CG',
  'congo (brazzaville)': 'CG',
  'congo (kinshasa)': 'CD',
  'congo brazzaville': 'CG',
  'congo kinshasa': 'CD',
  'congo, democratic republic of the': 'CD',
  'cook islands': 'CK',
  'costa rica': 'CR',
  'cote d\'ivoire': 'CI',
  croatia: 'HR',
  cuba: 'CU',
  'curaçao': 'CW',
  cyprus: 'CY',
  'czech republic': 'CZ',
  czechia: 'CZ',
  'côte d\'ivoire': 'CI',
  'democratic republic of the congo': 'CD',
  denmark: 'DK',
  djibouti: 'DJ',
  'dom. republic': 'DO',
  dominica: 'DM',
  'dominican rep.': 'DO',
  'dominican republic': 'DO',
  drc: 'CD',
  'east timor': 'TL',
  ecuador: 'EC',
  egypt: 'EG',
  'el salvador': 'SV',
  england: 'GB',
  'equatorial guinea': 'GQ',
  eritrea: 'ER',
  estonia: 'EE',
  eswatini: 'SZ',
  ethiopia: 'ET',
  'falkland islands': 'FK',
  'falkland islands (malvinas)': 'FK',
  'faroe islands': 'FO',
  fiji: 'FJ',
  finland: 'FI',
  france: 'FR',
  'french guiana': 'GF',
  'french polynesia': 'PF',
  'french southern territories': 'TF',
  gabon: 'GA',
  gambia: 'GM',
  georgia: 'GE',
  germany: 'DE',
  ghana: 'GH',
  gibraltar: 'GI',
  'great britain': 'GB',
  greece: 'GR',
  greenland: 'GL',
  grenada: 'GD',
  guadeloupe: 'GP',
  guam: 'GU',
  guatemala: 'GT',
  guernsey: 'GG',
  guinea: 'GN',
  'guinea-bissau': 'GW',
  guyana: 'GY',
  haiti: 'HT',
  'heard island and mcdonald islands': 'HM',
  holland: 'NL',
  'holy see': 'VA',
  honduras: 'HN',
  'hong kong': 'HK',
  'hong kong sar': 'HK',
  hungary: 'HU',
  iceland: 'IS',
  india: 'IN',
  indonesia: 'ID',
  iran: 'IR',
  'iran, islamic republic of': 'IR',
  iraq: 'IQ',
  ireland: 'IE',
  'isle of man': 'IM',
  israel: 'IL',
  italy: 'IT',
  'ivory coast': 'CI',
  jamaica: 'JM',
  japan: 'JP',
  jersey: 'JE',
  jordan: 'JO',
  kazakhstan: 'KZ',
  kenya: 'KE',
  kiribati: 'KI',
  korea: 'KR',
  'korea, democratic people\'s republic of': 'KP',
  'korea, republic of': 'KR',
  kuwait: 'KW',
  kyrgyzstan: 'KG',
  'lao people\'s democratic republic': 'LA',
  laos: 'LA',
  latvia: 'LV',
  lebanon: 'LB',
  lesotho: 'LS',
  liberia: 'LR',
  libya: 'LY',
  liechtenstein: 'LI',
  lithuania: 'LT',
  luxembourg: 'LU',
  macao: 'MO',
  'macao sar': 'MO',
  macau: 'MO',
  macedonia: 'MK',
  madagascar: 'MG',
  'mainland china': 'CN',
  malawi: 'MW',
  malaysia: 'MY',
  maldives: 'MV',
  mali: 'ML',
  malta: 'MT',
  'marshall islands': 'MH',
  martinique: 'MQ',
  mauritania: 'MR',
  mauritius: 'MU',
  mayotte: 'YT',
  mexico: 'MX',
  micronesia: 'FM',
  'micronesia, federated states of': 'FM',
  moldova: 'MD',
  'moldova, republic of': 'MD',
  monaco: 'MC',
  mongolia: 'MN',
  montenegro: 'ME',
  montserrat: 'MS',
  morocco: 'MA',
  mozambique: 'MZ',
  myanmar: 'MM',
  namibia: 'NA',
  nauru: 'NR',
  nepal: 'NP',
  netherlands: 'NL',
  'netherlands, kingdom of the': 'NL',
  'new caledonia': 'NC',
  'new zealand': 'NZ',
  nicaragua: 'NI',
  niger: 'NE',
  nigeria: 'NG',
  niue: 'NU',
  'norfolk island': 'NF',
  'north korea': 'KP',
  'north macedonia': 'MK',
  'northern ireland': 'GB',
  'northern mariana islands': 'MP',
  norway: 'NO',
  oman: 'OM',
  'p.r. china': 'CN',
  pakistan: 'PK',
  palau: 'PW',
  palestine: 'PS',
  'palestine, state of': 'PS',
  panama: 'PA',
  'papua new guinea': 'PG',
  paraguay: 'PY',
  peru: 'PE',
  philippines: 'PH',
  pitcairn: 'PN',
  poland: 'PL',
  portugal: 'PT',
  prc: 'CN',
  'puerto rico': 'PR',
  qatar: 'QA',
  'republic of korea': 'KR',
  'republic of the congo': 'CG',
  romania: 'RO',
  russia: 'RU',
  'russian federation': 'RU',
  rwanda: 'RW',
  'réunion': 'RE',
  'saint barthélemy': 'BL',
  'saint helena': 'SH',
  'saint helena, ascension and tristan da cunha': 'SH',
  'saint kitts and nevis': 'KN',
  'saint lucia': 'LC',
  'saint martin': 'MF',
  'saint martin (french part)': 'MF',
  'saint pierre and miquelon': 'PM',
  'saint vincent and the grenadines': 'VC',
  samoa: 'WS',
  'san marino': 'SM',
  'sao tome and principe': 'ST',
  'saudi arabia': 'SA',
  scotland: 'GB',
  senegal: 'SN',
  serbia: 'RS',
  seychelles: 'SC',
  'sierra leone': 'SL',
  singapore: 'SG',
  'sint maarten': 'SX',
  'sint maarten (dutch part)': 'SX',
  slovakia: 'SK',
  slovenia: 'SI',
  'solomon islands': 'SB',
  somalia: 'SO',
  'south africa': 'ZA',
  'south georgia and the south sandwich islands': 'GS',
  'south korea': 'KR',
  'south sudan': 'SS',
  spain: 'ES',
  'sri lanka': 'LK',
  sudan: 'SD',
  suriname: 'SR',
  'svalbard and jan mayen': 'SJ',
  swaziland: 'SZ',
  sweden: 'SE',
  switzerland: 'CH',
  syria: 'SY',
  'syrian arab republic': 'SY',
  taiwan: 'TW',
  'taiwan, province of china': 'TW',
  tajikistan: 'TJ',
  tanzania: 'TZ',
  'tanzania, united republic of': 'TZ',
  thailand: 'TH',
  'the netherlands': 'NL',
  'timor-leste': 'TL',
  togo: 'TG',
  tokelau: 'TK',
  tonga: 'TO',
  'trinidad and tobago': 'TT',
  tunisia: 'TN',
  turkey: 'TR',
  turkiye: 'TR',
  turkmenistan: 'TM',
  'turks and caicos islands': 'TC',
  tuvalu: 'TV',
  'türkiye': 'TR',
  'u.s.': 'US',
  'u.s. virgin islands': 'VI',
  'u.s.a.': 'US',
  uae: 'AE',
  uganda: 'UG',
  uk: 'GB',
  ukraine: 'UA',
  'united arab emirates': 'AE',
  'united kingdom': 'GB',
  'united kingdom of great britain and northern ireland': 'GB',
  'united states': 'US',
  'united states minor outlying islands': 'UM',
  'united states of america': 'US',
  uruguay: 'UY',
  usa: 'US',
  uzbekistan: 'UZ',
  vanuatu: 'VU',
  'vatican city': 'VA',
  venezuela: 'VE',
  'venezuela, bolivarian republic of': 'VE',
  'viet nam': 'VN',
  vietnam: 'VN',
  'virgin islands': 'VG',
  'virgin islands (british)': 'VG',
  'virgin islands (u.s.)': 'VI',
  wales: 'GB',
  'wallis and futuna': 'WF',
  'western sahara': 'EH',
  yemen: 'YE',
  zambia: 'ZM',
  zimbabwe: 'ZW',
  'åland islands': 'AX',
}

export interface CountryCode {
  /** The two-letter code, or the original text when it is not recognised. */
  code: string
  /** False when the name was not recognised and the operator must supply the code. */
  known: boolean
  /** The name a picker shows, when the code is known. */
  name: string
}

export function toIsoAlpha2(name: string | null | undefined): CountryCode {
  const text = (name ?? '').trim()
  if (!text) return { code: '', known: false, name: '' }
  // Already a code, as an item master or a hand-typed value may well be.
  if (/^[A-Za-z]{2}$/.test(text)) {
    const code = text.toUpperCase()
    return { code, known: code in NAMES, name: NAMES[code] ?? '' }
  }
  const hit = ISO_ALPHA2[text.toLowerCase()]
  return hit ? { code: hit, known: true, name: NAMES[hit] } : { code: text, known: false, name: '' }
}

/**
 * `Singapore` -> `SG - Singapore`, the form Ship Manager's country picker shows.
 *
 * Both halves on purpose. The commodity record stores the code, but the picker lists names,
 * so an operator given only `DO` has to translate and one given only `Dominican Republic`
 * has to look up the code.
 */
export function toCountryPickerLabel(name: string | null | undefined): string {
  const text = (name ?? '').trim()
  if (!text) return ''
  const { code, known, name: canonical } = toIsoAlpha2(text)
  return known ? `${code} - ${canonical}` : text
}
